# Generated by Django 3.1.4 on 2021-01-27 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 15, 28, 11, 438019), verbose_name='date published'),
        ),
    ]
